version: '3.9'

services:
  frontend:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
     - CHOKIDAR_USEPOLLING=true

  json-server:
    build: ./data/
    command: json-server -w /app/db.json -H 0.0.0.0 -p 3500
    ports:
      - 3500:3500
    volumes:
      - ./data/db.json:/app/db.json
  
  